START_SEITE = 1
SPIEL_SEITE = 2
ERGEBNIS_SEITE = 3
EINSTELUNGEN_SEITE = 4

ZEIT_SEKUNDEN = 60
MERKMAL_ZEIT_ABZUG = 10
RESTZEIT_FAKTOR = 1
ANZAHL_GIPFEL = 10
ANTWORT_OPTIONEN = 4

REGION_ALLE = "alle Berge"
REGION_BERNER_WALLISER_ALPEN = "Berner/Walliser Alpen"
REGION_INNERACHWEIZ_OSTSCHWEIZ = "Innerschweiz/Ostschweiz"
REGION_JURA_WESTSCHWEIZ = "Jura/Westschweiz"
REGION_TESSIN_GRAUBUENDEN = "Tessin/Graubünden"
